### ISSUE TITLE
Error in do.call(rbind, x) : second argument must be a list

### ISSUE THREAD

**Issue by joseADuranC** [gregorkastner/stochvol#18]
Good day:

I've been going through the article "Dealing with Stochastic Volatility in Time Series Using the R Package stochvol by Gregor Kastner" https://www.jstatsoft.org/article/view/v069i05 and the "code chunk number 27:" throws me an error, sorry if I ask something trivial, I'm new to all this statistics Bayesian and novice in handling the R language.

The mistake is:
Error in do.call(rbind, x) : second argument must be a list
In addition: Warning message:
'svsample2' is deprecated.
Use 'svsample_fast_cpp' instead.
See help("Deprecated")

how can i correct it?
Thank you in advance

**Comment by hdarjus** [comment]
Hi @judasnetwork, stochvol has received several big updates since 2016, and some of them break earlier code. Please either 

1. manually install the [R package from the JSS website](https://www.jstatsoft.org/index.php/jss/article/view/v069i05/3205) via `install.packages("path/to/downloaded/file/stochvol_1.2.3.tar.gz", type = "source", repos = NULL)` in case you would like to use the aforementioned paper, or
1. refer to our [latest publication in the same topic](https://doi.org/10.18637/jss.v100.i12), and then you should be able to use the CRAN version of stochvol.

Thanks for using stochvol!
